


spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/1804?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 1024
        min-idle: 100
        max-wait: 7000
        max-idle: 150
  application:
    name: clould-payment-service
#  activemq:
#    broker-url: tcp://localhost:61616
#    user: admin
#    password: admin
#  jms:
#    pub-sub-domain: false # false = Queue  true  = Topic
## 自己定义的队列名称
#myqueue: boot-activemq-queue
#mytopic: boot-activemq-topic


logging:
  level:
    com.dj.boot.mapper: debug



server:
  port: 8001


mybatis-plus:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.dj.cloud.pojo
  configuration:
    map-underscore-to-camel-case: true
#mybatis:
#  mapper-locations: classpath:mapper/*/*.xml
#  type-aliases-package: com.dj.cloud.pojo



eureka:
  client:
    # 表示将自己注册进去向服务注册中心eureka-server
    register-with-eureka: true
    #是否从eureka-server抓取已有的注册信息 默认为true 单节点无所谓 集群必须设置true才能配合ribbon使用负载均衡
    fetchRegistry: true

    service-url:
      #defaultZone: http://localhost:7001/eureka/ #单机
      defaultZone: http://eureka7002.com:7002/eureka, http://eureka7001.com:7001/eureka  #集群版
  instance:
    instance-id: payment8001
    prefer-ip-address: true  #访问路径可以显示IP地址

#    #Eureka客户端向服务端发送心跳的时间 单位秒 默认30
#    lease-renewal-interval-in-seconds: 30
#    #Eureka服务端在接收到最后一次心跳后等待时间上线 单位 秒  默认是90秒 超时就删除服务
#    lease-expiration-duration-in-seconds: 90




